[package]
name = "aragons-comics"
version = "0.1.0"
description = "Comic upload & management site."
repository = "https://github.com/SilkRose/Aragons-Comics"
authors = ["Silk Rose", "Meadowsys"]
edition = "2024"
license = "MIT"
publish = false

[dependencies]
actix-files = { version = "0.7.0" }
actix-web = { version = "4.15.0", features = ["macros"] }
anyhow = { version = "1.0.104" }
base64ct = { version = "1.8.3", features = ["std"] }
bon = { version = "3.10.1" }
chrono = { version = "0.4.45", features = ["serde"] }
dotenvy = { version = "0.15.7" }
lightningcss = { version = "1.0.0-alpha.72" }
maud = { version = "0.27.0" }
oxipng = { version = "10.2.1", default-features = false, features = ["zopfli"] }
pony = { git = "https://github.com/SilkRose/Pony", rev = "03cf3b82e88ab86b69cdfd04361175238051463b" }
rand = { version = "0.10.3", default-features = false, features = [
	"chacha",
	"sys_rng",
] }
reqwest = { version = "0.13.5", features = ["json", "form"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-json = { version = "1.0.151", package = "serde_json" }
serde-urlencoded = { version = "0.7.1", package = "serde_urlencoded" }
sqlx = { version = "0.9.0", default-features = false, features = [
	"chrono",
	"macros",
	"migrate",
	"postgres",
	"runtime-tokio",
	"tls-rustls",
] }
tokio = { version = "1.53.1", default-features = false }
url = "2.5.8"

[profile.dev]
opt-level = 0
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3
debug-assertions = false
lto = true
codegen-units = 1
