CREATE TABLE IF NOT EXISTS Comics (
	id            integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title         text        NOT NULL,
	url_stub      text        NOT NULL UNIQUE,
	page_hits     bigint      NOT NULL DEFAULT 0,
	date_modified timestamptz NOT NULL DEFAULT now(),
	date_created  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS Panels (
	comic_id         integer         NOT NULL,
	panel_number     decimal(10, 10) NOT NULL,
	panel_revision   integer         NOT NULL DEFAULT 0,
	bytes_original   integer         NOT NULL,
	bytes_compressed integer         NOT NULL,
	date_modified    timestamptz     NOT NULL DEFAULT now(),
	date_created     timestamptz     NOT NULL DEFAULT now(),

	CONSTRAINT Comic_panel_fk FOREIGN KEY (comic_id)
		REFERENCES Comics (id) ON DELETE CASCADE,

	CONSTRAINT Panels_bytes_original_ck
		CHECK (bytes_original > 0),

	CONSTRAINT Panels_bytes_compressed_ck
		CHECK (bytes_compressed > 0),

	CONSTRAINT Panels_pk PRIMARY KEY (comic_id, panel_number)
);
